version: "3"

services:
  frontend:
    image: xavgar9/employee-management-frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    image: xavgar9/employee-management-backend
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_DB=employeemanagement
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_DB=employeemanagement
