package testhelpers

import (
	users "Backend/myhandlers"
	"Backend/mymodels"
	"net/http"
)

// CasesGetAllUsers test cases for the GetAllUsers endpoint
func CasesGetAllUsers() mymodels.AllTest {
	return mymodels.AllTest{
		{
			Method:       "GET",
			URL:          "/Users/GetAllUsers",
			Function:     users.GetAllUsers,
			Body:         "",
			ExpectedBody: `[{"ID":3,"FirstLastName":"PALACIO","SecondLastName":"MARTINEZ","FirstName":"MICHAEL","OtherNames":"DARIO","CountryID":2,"Country":"ESTADOS UNIDOS","IdTypes":1,"IdTypesName":"CEDULA DE CIUDADANIA","IdentificationDocument":"2233224411","Email":"michael.palacio1@cidenet.com","StartDate":"2021-03-26 10:30:00","AreaID":3,"AreaName":"COMPRAS","Status":"ACTIVO"},{"ID":2,"FirstLastName":"PALACIO","SecondLastName":"GUZMAN","FirstName":"MICHAEL","OtherNames":"ANDRES","CountryID":2,"Country":"ESTADOS UNIDOS","IdTypes":1,"IdTypesName":"CEDULA DE CIUDADANIA","IdentificationDocument":"1133224411","Email":"michael.palacio@cidenet.com","StartDate":"2021-03-26 10:00:00","AreaID":1,"AreaName":"ADMINISTRACION","Status":"ACTIVO"},{"ID":1,"FirstLastName":"GARZON","SecondLastName":"LOPEZ","FirstName":"XAVIER","OtherNames":"","CountryID":1,"Country":"COLOMBIA","IdTypes":1,"IdTypesName":"CEDULA DE CIUDADANIA","IdentificationDocument":"1144114411","Email":"xavier.garzon@cidenet.com","StartDate":"2021-03-25 14:00:00","AreaID":1,"AreaName":"ADMINISTRACION","Status":"ACTIVO"}]`,
			StatusCode:   http.StatusOK,
		},
	}
}

// CasesGetUser test cases for the GetUser endpoint
func CasesGetUser() mymodels.AllTest {
	return mymodels.AllTest{
		{
			Method:       "GET",
			URL:          "/Users/GetUser?idddd=1",
			Function:     users.GetUser,
			Body:         "",
			ExpectedBody: `ID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "GET",
			URL:          "/Users/GetUser?id=",
			Function:     users.GetUser,
			Body:         "",
			ExpectedBody: `ID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "GET",
			URL:          "/Users/GetUser",
			Function:     users.GetUser,
			Body:         "",
			ExpectedBody: `ID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "GET",
			URL:          "/Users/GetUser?id=1",
			Function:     users.GetUser,
			Body:         "",
			ExpectedBody: `{"ID":1,"FirstLastName":"GARZON","SecondLastName":"LOPEZ","FirstName":"XAVIER","OtherNames":"","CountryID":1,"Country":"COLOMBIA","IdTypes":1,"IdTypesName":"CEDULA DE CIUDADANIA","IdentificationDocument":"1144114411","Email":"xavier.garzon@cidenet.com","StartDate":"2021-03-25 14:00:00","AreaID":1,"AreaName":"ADMINISTRACION","Status":"ACTIVO"}`,
			StatusCode:   http.StatusOK,
		},
		{
			Method:       "GET",
			URL:          "/Users/GetUser?id=2",
			Function:     users.GetUser,
			Body:         "",
			ExpectedBody: `{"ID":2,"FirstLastName":"PALACIO","SecondLastName":"GUZMAN","FirstName":"MICHAEL","OtherNames":"ANDRES","CountryID":2,"Country":"ESTADOS UNIDOS","IdTypes":1,"IdTypesName":"CEDULA DE CIUDADANIA","IdentificationDocument":"1133224411","Email":"michael.palacio@cidenet.com","StartDate":"2021-03-26 10:00:00","AreaID":1,"AreaName":"ADMINISTRACION","Status":"ACTIVO"}`,
			StatusCode:   http.StatusOK,
		},
		{
			Method:       "GET",
			URL:          "/Users/GetUser?id=3",
			Function:     users.GetUser,
			Body:         "",
			ExpectedBody: `{"ID":3,"FirstLastName":"PALACIO","SecondLastName":"MARTINEZ","FirstName":"MICHAEL","OtherNames":"DARIO","CountryID":2,"Country":"ESTADOS UNIDOS","IdTypes":1,"IdTypesName":"CEDULA DE CIUDADANIA","IdentificationDocument":"2233224411","Email":"michael.palacio1@cidenet.com","StartDate":"2021-03-26 10:30:00","AreaID":3,"AreaName":"COMPRAS","Status":"ACTIVO"}`,
			StatusCode:   http.StatusOK,
		},
		{
			Method:       "GET",
			URL:          "/Users/GetUser?id=15",
			Function:     users.GetUser,
			Body:         "",
			ExpectedBody: ``,
			StatusCode:   http.StatusOK,
		},
	}
}

// CasesUpdateUser bla bla...
func CasesUpdateUser() mymodels.AllTest {
	return mymodels.AllTest{
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":1,"FirstLastName":"OCORO","SecondLastName":"HOYUELO","FirstName":"ANDRES","OtherNames":"","CountryID":2,"IdTypes":1,"IdentificationDocument":"66666666","Email":"andres.hoyuelo@cidenet.com","StartDate":"2021-03-26 21:30:00","AreaID":4,"Status":"ACTIVO"}`,
			ExpectedBody: `{"ID":1,"FirstLastName":"OCORO","SecondLastName":"HOYUELO","FirstName":"ANDRES","OtherNames":"","CountryID":2,"IdTypes":1,"IdentificationDocument":"66666666","Email":"andres.hoyuelo@cidenet.com","StartDate":"2021-03-26 21:30:00","AreaID":4,"Status":"ACTIVO"}`,
			StatusCode:   http.StatusOK,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			StatusCode:   http.StatusOK,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `ID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":,FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `ID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `FirstLastName is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `FirstLastName is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `SecondLastName is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `SecondLastName is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `FirstName is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `FirstName is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `CountryID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":"1","IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `CountryID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `IdTypes is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":"2","IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `IdTypes is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `IdentificationDocument is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `IdentificationDocument is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `Email is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `Email is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `StartDate is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `StartDate is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","Status":"ACTIVO"}`,
			ExpectedBody: `AreaID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":"1","Status":"ACTIVO"}`,
			ExpectedBody: `AreaID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1}`,
			ExpectedBody: `Status is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":""}`,
			ExpectedBody: `Status is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":1,"FirstLastName":"GARZON","SecondLastName":"LOPEZ","FirstName":"XAVIER","OtherNames":"","CountryID":1,"Country":"COLOMBIA","IdTypes":1,"IdentificationDocument":"1144114411","Email":"xavier.garzon@cidenet.com","StartDate":"2021-03-25 14:00:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `{"ID":1,"FirstLastName":"GARZON","SecondLastName":"LOPEZ","FirstName":"XAVIER","OtherNames":"","CountryID":1,"Country":"COLOMBIA","IdTypes":1,"IdentificationDocument":"1144114411","Email":"xavier.garzon@cidenet.com","StartDate":"2021-03-25 14:00:00","AreaID":1,"Status":"ACTIVO"}`,
			StatusCode:   http.StatusOK,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"PALACIO","SecondLastName":"GUZMAN","FirstName":"MICHAEL","OtherNames":"ANDRES","CountryID":2,"IdTypes":1,"IdentificationDocument":"1133224411","Email":"michael.palacio@cidenet.com","StartDate":"2021-03-26 10:00:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `{"ID":2,"FirstLastName":"PALACIO","SecondLastName":"GUZMAN","FirstName":"MICHAEL","OtherNames":"ANDRES","CountryID":2,"IdTypes":1,"IdentificationDocument":"1133224411","Email":"michael.palacio@cidenet.com","StartDate":"2021-03-26 10:00:00","AreaID":1,"Status":"ACTIVO"}`,
			StatusCode:   http.StatusOK,
		},
	}
}

// CasesCreateUser bla bla...
func CasesCreateUser() mymodels.AllTest {
	return mymodels.AllTest{
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"OCORO","SecondLastName":"HOYUELO","FirstName":"ANDRES","OtherNames":"","CountryID":2,"IdTypes":1,"IdentificationDocument":"66666666","Email":"andres.hoyuelo@cidenet.com","StartDate":"2021-03-26 21:30:00","AreaID":4,"Status":"ACTIVO"}`,
			ExpectedBody: `{"ID":4,"FirstLastName":"OCORO","SecondLastName":"HOYUELO","FirstName":"ANDRES","OtherNames":"","CountryID":2,"IdTypes":1,"IdentificationDocument":"66666666","Email":"andres.hoyuelo@cidenet.com","StartDate":"2021-03-26 21:30:00","AreaID":4,"Status":"ACTIVO"}`,
			StatusCode:   http.StatusCreated,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `{"ID":5,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			StatusCode:   http.StatusCreated,
		},

		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `FirstLastName is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `FirstLastName is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `SecondLastName is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `SecondLastName is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `FirstName is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `FirstName is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `CountryID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":"1","IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `CountryID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `IdTypes is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":"2","IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `IdTypes is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `IdentificationDocument is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `IdentificationDocument is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `Email is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `Email is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `StartDate is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `StartDate is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","Status":"ACTIVO"}`,
			ExpectedBody: `AreaID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":"1","Status":"ACTIVO"}`,
			ExpectedBody: `AreaID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1}`,
			ExpectedBody: `Status is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"IdTypes":2,"IdentificationDocument":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27 15:34:00","AreaID":1,"Status":""}`,
			ExpectedBody: `Status is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
	}
}

// CasesDeleteUser bla bla...
func CasesDeleteUser() mymodels.AllTest {
	return mymodels.AllTest{
		{
			Method:       "DELETE",
			URL:          "/Users/DeleteUser",
			Function:     users.DeleteUser,
			Body:         `{"ID":10}`,
			ExpectedBody: `No rows deleted`,
			StatusCode:   http.StatusOK,
		},
		{
			Method:       "DELETE",
			URL:          "/Users/DeleteUser",
			Function:     users.DeleteUser,
			Body:         `{"ID":4}`,
			ExpectedBody: `One row deleted`,
			StatusCode:   http.StatusOK,
		},
		{
			Method:       "DELETE",
			URL:          "/Users/DeleteUser",
			Function:     users.DeleteUser,
			Body:         `{"ID":5}`,
			ExpectedBody: `One row deleted`,
			StatusCode:   http.StatusOK,
		},
		{
			Method:       "DELETE",
			URL:          "/Users/DeleteUser",
			Function:     users.DeleteUser,
			Body:         `{"ID":Test}`,
			ExpectedBody: `ID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
	}
}
