package testhelpers

import (
	users "Backend/myhandlers"
	"Backend/mymodels"
	"net/http"
)

// CasesGetAllUsers test cases for the GetAllUsers endpoint
func CasesGetAllUsers() mymodels.AllTest {
	return mymodels.AllTest{
		{
			Method:       "GET",
			URL:          "/Users/GetAllUsers",
			Function:     users.GetAllUsers,
			Body:         "",
			ExpectedBody: `[{"ID":11,"FirstLastName":"ESTUPINAN","SecondLastName":"TAVAREZ","FirstName":"MARIANA","OtherNames":"","CountryID":2,"Country":"ESTADOS UNIDOS","DocumentTypeID":1,"DocumentType":"CEDULA DE CIUDADANIA","Document":"1133224411","Email":"mariana.estupinan@cidenet.com.us","StartDate":"26-03-2021","AreaID":7,"Area":"OTROS","Status":"ACTIVO"},{"ID":10,"FirstLastName":"RODRIGUEZ","SecondLastName":"MARIN","FirstName":"SOFIA","OtherNames":"","CountryID":2,"Country":"ESTADOS UNIDOS","DocumentTypeID":1,"DocumentType":"CEDULA DE CIUDADANIA","Document":"1133224411","Email":"sofia.rodriguez@cidenet.com.us","StartDate":"26-03-2021","AreaID":6,"Area":"SERVICIOS VARIOS","Status":"ACTIVO"},{"ID":9,"FirstLastName":"PINEDA","SecondLastName":"DUQUE","FirstName":"ANDREA","OtherNames":"","CountryID":1,"Country":"COLOMBIA","DocumentTypeID":1,"DocumentType":"CEDULA DE CIUDADANIA","Document":"1133224411","Email":"andrea.pineda@cidenet.com.co","StartDate":"26-03-2021","AreaID":5,"Area":"TALENTO HUMANO","Status":"ACTIVO"},{"ID":8,"FirstLastName":"PAZ","SecondLastName":"FERNADEZ","FirstName":"MARCO","OtherNames":"DE LA CALLE","CountryID":2,"Country":"ESTADOS UNIDOS","DocumentTypeID":1,"DocumentType":"CEDULA DE CIUDADANIA","Document":"1133224411","Email":"marco.paz@cidenet.com.us","StartDate":"26-03-2021","AreaID":4,"Area":"INFRAESTRUCTURA","Status":"ACTIVO"},{"ID":7,"FirstLastName":"HERNANDEZ","SecondLastName":"GONZALEZ","FirstName":"ANDRES","OtherNames":"","CountryID":1,"Country":"COLOMBIA","DocumentTypeID":1,"DocumentType":"CEDULA DE CIUDADANIA","Document":"1133224411","Email":"andres.hernandez@cidenet.com.co","StartDate":"26-03-2021","AreaID":2,"Area":"FINANCIERA","Status":"ACTIVO"},{"ID":6,"FirstLastName":"GOMEZ","SecondLastName":"HERNANDEZ","FirstName":"ANDRES","OtherNames":"ANDRES","CountryID":1,"Country":"COLOMBIA","DocumentTypeID":1,"DocumentType":"CEDULA DE CIUDADANIA","Document":"1133224411","Email":"andres.gomez@cidenet.com.co","StartDate":"26-03-2021","AreaID":1,"Area":"ADMINISTRACION","Status":"ACTIVO"},{"ID":5,"FirstLastName":"GARZON","SecondLastName":"GUTIERREZ","FirstName":"XAVIER","OtherNames":"ANTONIO","CountryID":2,"Country":"ESTADOS UNIDOS","DocumentTypeID":2,"DocumentType":"CEDULA DE EXTRANJERIA","Document":"TR-0105454","Email":"xavier.garzon5@cidenet.com.us","StartDate":"25-03-2021","AreaID":1,"Area":"ADMINISTRACION","Status":"ACTIVO"},{"ID":4,"FirstLastName":"GARZON","SecondLastName":"GUTIERREZ","FirstName":"XAVIER","OtherNames":"","CountryID":2,"Country":"ESTADOS UNIDOS","DocumentTypeID":1,"DocumentType":"CEDULA DE CIUDADANIA","Document":"1144114422","Email":"xavier.garzon@cidenet.com.us","StartDate":"25-03-2021","AreaID":2,"Area":"FINANCIERA","Status":"ACTIVO"},{"ID":3,"FirstLastName":"PALACIO","SecondLastName":"MARTINEZ","FirstName":"MICHAEL","OtherNames":"DARIO","CountryID":1,"Country":"COLOMBIA","DocumentTypeID":1,"DocumentType":"CEDULA DE CIUDADANIA","Document":"2233224411","Email":"michael.palacio3@cidenet.com.co","StartDate":"26-03-2021","AreaID":3,"Area":"COMPRAS","Status":"ACTIVO"},{"ID":2,"FirstLastName":"PALACIO","SecondLastName":"GUZMAN","FirstName":"MICHAEL","OtherNames":"ANDRES","CountryID":1,"Country":"COLOMBIA","DocumentTypeID":1,"DocumentType":"CEDULA DE CIUDADANIA","Document":"1133224411","Email":"michael.palacio@cidenet.com.co","StartDate":"26-03-2021","AreaID":4,"Area":"INFRAESTRUCTURA","Status":"ACTIVO"},{"ID":1,"FirstLastName":"GARZON","SecondLastName":"LOPEZ","FirstName":"XAVIER","OtherNames":"","CountryID":1,"Country":"COLOMBIA","DocumentTypeID":1,"DocumentType":"CEDULA DE CIUDADANIA","Document":"1144114411","Email":"xavier.garzon@cidenet.com.co","StartDate":"25-03-2021","AreaID":1,"Area":"ADMINISTRACION","Status":"ACTIVO"}]`,
			StatusCode:   http.StatusOK,
		},
	}
}

// CasesGetUser test cases for the GetUser endpoint
func CasesGetUser() mymodels.AllTest {
	return mymodels.AllTest{
		{
			Method:       "GET",
			URL:          "/Users/GetUser?idddd=1",
			Function:     users.GetUser,
			Body:         "",
			ExpectedBody: `ID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "GET",
			URL:          "/Users/GetUser?id=",
			Function:     users.GetUser,
			Body:         "",
			ExpectedBody: `ID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "GET",
			URL:          "/Users/GetUser",
			Function:     users.GetUser,
			Body:         "",
			ExpectedBody: `ID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "GET",
			URL:          "/Users/GetUser?id=1",
			Function:     users.GetUser,
			Body:         "",
			ExpectedBody: `{"ID":1,"FirstLastName":"GARZON","SecondLastName":"LOPEZ","FirstName":"XAVIER","OtherNames":"","CountryID":1,"Country":"COLOMBIA","DocumentTypeID":1,"DocumentType":"CEDULA DE CIUDADANIA","Document":"1144114411","Email":"xavier.garzon@cidenet.com.co","StartDate":"25-03-2021","AreaID":1,"Area":"ADMINISTRACION","Status":"ACTIVO"}`,
			StatusCode:   http.StatusOK,
		},
		{
			Method:       "GET",
			URL:          "/Users/GetUser?id=2",
			Function:     users.GetUser,
			Body:         "",
			ExpectedBody: `{"ID":2,"FirstLastName":"PALACIO","SecondLastName":"GUZMAN","FirstName":"MICHAEL","OtherNames":"ANDRES","CountryID":1,"Country":"COLOMBIA","DocumentTypeID":1,"DocumentType":"CEDULA DE CIUDADANIA","Document":"1133224411","Email":"michael.palacio@cidenet.com.co","StartDate":"26-03-2021","AreaID":4,"Area":"INFRAESTRUCTURA","Status":"ACTIVO"}`,
			StatusCode:   http.StatusOK,
		},
		{
			Method:       "GET",
			URL:          "/Users/GetUser?id=3",
			Function:     users.GetUser,
			Body:         "",
			ExpectedBody: `{"ID":3,"FirstLastName":"PALACIO","SecondLastName":"MARTINEZ","FirstName":"MICHAEL","OtherNames":"DARIO","CountryID":1,"Country":"COLOMBIA","DocumentTypeID":1,"DocumentType":"CEDULA DE CIUDADANIA","Document":"2233224411","Email":"michael.palacio3@cidenet.com.co","StartDate":"26-03-2021","AreaID":3,"Area":"COMPRAS","Status":"ACTIVO"}`,
			StatusCode:   http.StatusOK,
		},
		{
			Method:       "GET",
			URL:          "/Users/GetUser?id=25",
			Function:     users.GetUser,
			Body:         "",
			ExpectedBody: ``,
			StatusCode:   http.StatusOK,
		},
	}
}

// CasesUpdateUser bla bla...
func CasesUpdateUser() mymodels.AllTest {
	return mymodels.AllTest{
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":1,"FirstLastName":"OCORO","SecondLastName":"HOYUELO","FirstName":"ANDRES","OtherNames":"","CountryID":2,"DocumentTypeID":1,"Document":"66666666","StartDate":"2021-03-26","AreaID":4,"Status":"ACTIVO"}`,
			ExpectedBody: `{"ID":1,"FirstLastName":"OCORO","SecondLastName":"HOYUELO","FirstName":"ANDRES","OtherNames":"","CountryID":2,"Country":"ESTADOS UNIDOS","DocumentTypeID":1,"DocumentType":"CEDULA DE CIUDADANIA","Document":"66666666","Email":"andres.ocoro@cidenet.com.us","StartDate":"26-03-2021","AreaID":4,"Area":"INFRAESTRUCTURA","Status":"ACTIVO"}`,
			StatusCode:   http.StatusOK,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"Country":"COLOMBIA","DocumentTypeID":2,"DocumentType":"CEDULA DE EXTRANJERIA","Document":"ESP0102A","Email":"mariana.suarez@cidenet.com.co","StartDate":"27-03-2021","AreaID":1,"Area":"ADMINISTRACION","Status":"ACTIVO"}`,
			StatusCode:   http.StatusOK,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `ID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":,FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `ID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `FirstLastName is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `FirstLastName is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `SecondLastName is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `SecondLastName is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `FirstName is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `FirstName is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `CountryID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":"1","DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `CountryID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `DocumentTypeID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":"2","Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `DocumentTypeID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `Document is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `Document is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `StartDate is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `StartDate is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","Status":"ACTIVO"}`,
			ExpectedBody: `AreaID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":"1","Status":"ACTIVO"}`,
			ExpectedBody: `AreaID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1}`,
			ExpectedBody: `Status is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":""}`,
			ExpectedBody: `Status is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":1,"FirstLastName":"GARZON","SecondLastName":"LOPEZ","FirstName":"XAVIER","OtherNames":"","CountryID":1,"Country":"COLOMBIA","DocumentTypeID":1,"Document":"1144114411","StartDate":"2021-03-25","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `{"ID":1,"FirstLastName":"GARZON","SecondLastName":"LOPEZ","FirstName":"XAVIER","OtherNames":"","CountryID":1,"Country":"COLOMBIA","DocumentTypeID":1,"DocumentType":"CEDULA DE CIUDADANIA","Document":"1144114411","Email":"xavier.garzon@cidenet.com.co","StartDate":"25-03-2021","AreaID":1,"Area":"ADMINISTRACION","Status":"ACTIVO"}`,
			StatusCode:   http.StatusOK,
		},
		{
			Method:       "POST",
			URL:          "/Users/UpdateUser",
			Function:     users.UpdateUser,
			Body:         `{"ID":2,"FirstLastName":"PALACIO","SecondLastName":"GUZMAN","FirstName":"MICHAEL","OtherNames":"ANDRES","CountryID":2,"DocumentTypeID":1,"Document":"1133224411","StartDate":"2021-03-26","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `{"ID":2,"FirstLastName":"PALACIO","SecondLastName":"GUZMAN","FirstName":"MICHAEL","OtherNames":"ANDRES","CountryID":2,"Country":"ESTADOS UNIDOS","DocumentTypeID":1,"DocumentType":"CEDULA DE CIUDADANIA","Document":"1133224411","Email":"michael.palacio@cidenet.com.us","StartDate":"26-03-2021","AreaID":1,"Area":"ADMINISTRACION","Status":"ACTIVO"}`,
			StatusCode:   http.StatusOK,
		},
	}
}

// CasesCreateUser bla bla...
func CasesCreateUser() mymodels.AllTest {
	return mymodels.AllTest{
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"OCORO","SecondLastName":"HOYUELO","FirstName":"ANDRES","OtherNames":"","CountryID":2,"DocumentTypeID":1,"Document":"66666666","StartDate":"2021-03-26","AreaID":4,"Status":"ACTIVO"}`,
			ExpectedBody: `{"ID":12,"FirstLastName":"OCORO","SecondLastName":"HOYUELO","FirstName":"ANDRES","OtherNames":"","CountryID":2,"Country":"ESTADOS UNIDOS","DocumentTypeID":1,"DocumentType":"CEDULA DE CIUDADANIA","Document":"66666666","Email":"andres.ocoro@cidenet.com.us","StartDate":"26-03-2021","AreaID":4,"Area":"INFRAESTRUCTURA","Status":"ACTIVO"}`,
			StatusCode:   http.StatusCreated,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"OCORO","SecondLastName":"HOYUELO","FirstName":"ANDRES","OtherNames":"","CountryID":2,"DocumentTypeID":1,"Document":"66666666","StartDate":"2021-03-26","AreaID":4,"Status":"ACTIVO"}`,
			ExpectedBody: `{"ID":13,"FirstLastName":"OCORO","SecondLastName":"HOYUELO","FirstName":"ANDRES","OtherNames":"","CountryID":2,"Country":"ESTADOS UNIDOS","DocumentTypeID":1,"DocumentType":"CEDULA DE CIUDADANIA","Document":"66666666","Email":"andres.ocoro13@cidenet.com.us","StartDate":"26-03-2021","AreaID":4,"Area":"INFRAESTRUCTURA","Status":"ACTIVO"}`,
			StatusCode:   http.StatusCreated,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `{"ID":14,"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"Country":"COLOMBIA","DocumentTypeID":2,"DocumentType":"CEDULA DE EXTRANJERIA","Document":"ESP0102A","Email":"mariana.suarez@cidenet.com.co","StartDate":"27-03-2021","AreaID":1,"Area":"ADMINISTRACION","Status":"ACTIVO"}`,
			StatusCode:   http.StatusCreated,
		},

		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `FirstLastName is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `FirstLastName is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `SecondLastName is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `SecondLastName is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `FirstName is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `FirstName is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `CountryID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":"1","DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `CountryID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `DocumentTypeID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":"2","Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `DocumentTypeID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `Document is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `Document is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `StartDate is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"","AreaID":1,"Status":"ACTIVO"}`,
			ExpectedBody: `StartDate is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","Status":"ACTIVO"}`,
			ExpectedBody: `AreaID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":"1","Status":"ACTIVO"}`,
			ExpectedBody: `AreaID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1}`,
			ExpectedBody: `Status is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
		{
			Method:       "POST",
			URL:          "/Users/CreateUser",
			Function:     users.CreateUser,
			Body:         `{"FirstLastName":"SUAREZ","SecondLastName":"GUZMAN","FirstName":"MARIANA","OtherNames":"MARTINA","CountryID":1,"DocumentTypeID":2,"Document":"ESP0102A","Email":"mariana.suarez@cidenet.com","StartDate":"2021-03-27","AreaID":1,"Status":""}`,
			ExpectedBody: `Status is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
	}
}

// CasesDeleteUser bla bla...
func CasesDeleteUser() mymodels.AllTest {
	return mymodels.AllTest{
		{
			Method:       "DELETE",
			URL:          "/Users/DeleteUser",
			Function:     users.DeleteUser,
			Body:         `{"ID":55}`,
			ExpectedBody: `No rows deleted`,
			StatusCode:   http.StatusOK,
		},
		{
			Method:       "DELETE",
			URL:          "/Users/DeleteUser",
			Function:     users.DeleteUser,
			Body:         `{"ID":12}`,
			ExpectedBody: `One row deleted`,
			StatusCode:   http.StatusOK,
		},
		{
			Method:       "DELETE",
			URL:          "/Users/DeleteUser",
			Function:     users.DeleteUser,
			Body:         `{"ID":13}`,
			ExpectedBody: `One row deleted`,
			StatusCode:   http.StatusOK,
		},
		{
			Method:       "DELETE",
			URL:          "/Users/DeleteUser",
			Function:     users.DeleteUser,
			Body:         `{"ID":14}`,
			ExpectedBody: `One row deleted`,
			StatusCode:   http.StatusOK,
		},
		{
			Method:       "DELETE",
			URL:          "/Users/DeleteUser",
			Function:     users.DeleteUser,
			Body:         `{"ID":Test}`,
			ExpectedBody: `ID is empty or not valid`,
			StatusCode:   http.StatusBadRequest,
		},
	}
}
